In [1]:
import torch
from torch import nn


input_size = 2
ouput_size = 4
num_layers = 1
bidirectional = False

model = nn.RNN(
    input_size=input_size,
    hidden_size=ouput_size,
    num_layers=num_layers,
    nonlinearity="relu",
    batch_first=True,
    bidirectional=bidirectional,
    bias=False
)
c=1
for name, param in model.named_parameters():
    if 'weight' in name:
        nn.init.constant_(param, 2.0)
        print('xh가중치 또는 hh가중치:',param)
        #가중치를 조절한 다음 행렬곱을 통해 입력값과 은닉값의 차원을 맞춰준다.
        

batch_size = 1
sequence_len =5

inputs = torch.Tensor( batch_size,sequence_len, input_size).fill_(2)
h_0 = torch.Tensor(num_layers * (int(bidirectional) + 1), batch_size, ouput_size).fill_(2)
print('초기 hidden 값:',h_0)
outputs, hidden = model(inputs, h_0)
print(outputs.shape)
print(hidden.shape)

xh가중치 또는 hh가중치: Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
xh가중치 또는 hh가중치: Parameter containing:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], requires_grad=True)
초기 hidden 값: tensor([[[2., 2., 2., 2.]]])
torch.Size([1, 5, 4])
torch.Size([1, 1, 4])


In [3]:

print(inputs) #배치크기 시퀀스 크기 데이터 크기


tensor([[[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]])


In [4]:
print(outputs)#배치크기 은닉상태 크기 시퀀스길이 

tensor([[[2.4000e+01, 2.4000e+01, 2.4000e+01, 2.4000e+01],
         [2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02],
         [1.6080e+03, 1.6080e+03, 1.6080e+03, 1.6080e+03],
         [1.2872e+04, 1.2872e+04, 1.2872e+04, 1.2872e+04],
         [1.0298e+05, 1.0298e+05, 1.0298e+05, 1.0298e+05]]],
       grad_fn=<TransposeBackward1>)


In [5]:
print(hidden)

tensor([[[102984., 102984., 102984., 102984.]]], grad_fn=<StackBackward0>)


In [11]:

w=torch.tensor([[2,2,2,2],
                [2,2,2,2],
                [2,2,2,2],
                [2,2,2,2]])

v=torch.tensor([[2,2,2,2]])
v=torch.transpose(v,0,1)
print(torch.transpose(w@v,0,1))#행렬곱

w1=torch.tensor([[2,2],
                [2,2],
                [2,2],
                [2,2]])

v1=torch.tensor([[2,2]])
v1=torch.transpose(v1,0,1)
print(torch.transpose(w1@v1,0,1))

print(torch.transpose(w1@v1,0,1)+torch.transpose(w@v,0,1))

tensor([[16, 16, 16, 16]])
tensor([[8, 8, 8, 8]])
tensor([[24, 24, 24, 24]])
