In [23]:
import torch
from torch import nn


input_size = 2
ouput_size = 4
num_layers = 1
bidirectional = True

model = nn.RNN(
    input_size=input_size,
    hidden_size=ouput_size,
    num_layers=num_layers,
    nonlinearity="relu",
    batch_first=True,
    bidirectional=bidirectional,
    bias=False
)
c=1
for name, param in model.named_parameters():
    if 'weight' in name:
        nn.init.constant_(param, 2.0)
        print('xh가중치 또는 hh가중치:',param)
        #가중치를 조절한 다음 입력과 은닉값의 데이터를 가중치와 행렬곱이 아닌 벡터곱을해 버린다음 안의 값을 다 더해 차원을 맞춰서 더한다.
        #와 대가리 터진다.
        

batch_size = 1
sequence_len =5

inputs = torch.Tensor( batch_size,sequence_len, input_size).fill_(2)
h_0 = torch.Tensor(num_layers * (int(bidirectional) + 1), batch_size, ouput_size).fill_(2)
print('초기 hidden 값:',h_0)
outputs, hidden = model(inputs, h_0)
print(outputs.shape)
print(hidden.shape)

xh가중치 또는 hh가중치: Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
xh가중치 또는 hh가중치: Parameter containing:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], requires_grad=True)
xh가중치 또는 hh가중치: Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
xh가중치 또는 hh가중치: Parameter containing:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], requires_grad=True)
초기 hidden 값: tensor([[[2., 2., 2., 2.]],

        [[2., 2., 2., 2.]]])
torch.Size([1, 5, 8])
torch.Size([2, 1, 4])


In [24]:

print(inputs) #배치크기 시퀀스 크기 데이터 크기


tensor([[[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]])


In [25]:
print(outputs)#배치크기 은닉상태 크기 시퀀스길이 

tensor([[[2.4000e+01, 2.4000e+01, 2.4000e+01, 2.4000e+01, 1.0298e+05,
          1.0298e+05, 1.0298e+05, 1.0298e+05],
         [2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02, 1.2872e+04,
          1.2872e+04, 1.2872e+04, 1.2872e+04],
         [1.6080e+03, 1.6080e+03, 1.6080e+03, 1.6080e+03, 1.6080e+03,
          1.6080e+03, 1.6080e+03, 1.6080e+03],
         [1.2872e+04, 1.2872e+04, 1.2872e+04, 1.2872e+04, 2.0000e+02,
          2.0000e+02, 2.0000e+02, 2.0000e+02],
         [1.0298e+05, 1.0298e+05, 1.0298e+05, 1.0298e+05, 2.4000e+01,
          2.4000e+01, 2.4000e+01, 2.4000e+01]]], grad_fn=<TransposeBackward1>)


In [26]:
print(hidden)

tensor([[[102984., 102984., 102984., 102984.]],

        [[102984., 102984., 102984., 102984.]]], grad_fn=<StackBackward0>)


In [ ]:
#텐서 연산 및 차원 조작
#참고로 텐서의 자료형이 다르면 연산이 불가능하다.

v=torch.tensor([[2,2,2,2],
                [2,2,2,2],
                [2,2,2,2],
                [2,2,2,2]])

w=torch.tensor([[2,2,2,2]])
print(v*w)#벡터 

for i in v*w:
    print(i.sum(),end=' ')
print('\n')
v1=torch.tensor([[2,2],
                [2,2],
                [2,2],
                [2,2]])

w1=torch.tensor([[2,2]])

print(v1*w1)

for i in v1*w1:
    print(i.sum(),end=' ')
print('')

#출력된 두 텐서들을 더하면 결국 (24,24,24,24)가 된다.